### ISSUE TITLE
Hazy not working in the new update

### ISSUE THREAD

**Issue by quincynyan** [Astromations/Hazy#107] opened 2024-06-06 11:38 UTC
Using Spotify installation from .exe, and Hazy from automatic installation, not marketplace. Blank Black background, no edit/customize button on top.

**Comment by Astromations** [comment] 2024-06-06 13:29
Sometimes the javascript doesn't run until you play a song. Please try that if you haven't already.

**Comment by quincynyan** [comment] 2024-06-06 13:46
nope

https://cdn.nekonyan.fun/Spotify_gaI8ZtcZ5c.gif

**Comment by Astromations** [comment] 2024-06-06 13:48
Got it. I'll take a look as soon as I can.

**Comment by quincynyan** [comment] 2024-06-06 13:50
![image](https://github.com/Astromations/Hazy/assets/65074780/a626f20c-3af2-44c5-839e-689400fb4ae7)

**Comment by sanoojes** [comment] 2024-06-29 12:38
can you update the theme and check it is resolved @quincynyan

**Comment by quincynyan** [comment] 2024-06-29 14:41
@sanoojes nope 

![image](https://github.com/Astromations/Hazy/assets/65074780/0583dfc6-a3bd-4b4d-bbf4-e0453d1449d0)

![image](https://github.com/Astromations/Hazy/assets/65074780/54f06d74-bfcb-48ba-9ac2-d21e10ec0f3c)

**Comment by quincynyan** [comment] 2024-06-29 14:45
![image](https://github.com/Astromations/Hazy/assets/65074780/51b17b87-9077-4abd-b94a-cab0f70f585c)

Tried with marketplace, same result.

**Comment by sanoojes** [comment] 2024-06-29 15:12
Hey ! Sorry to hear you're having trouble. 

The Microsoft Store version of Spotify has limited compatibility with Spicetify. Here's what you can try:

1. **Test with other themes:** See if the problem persists with different Spicetify themes. This will help to find whether the issue is with a specific theme or the Microsoft Store version itself.

2. **Install Spotify from the official website:** If the problem occurs with multiple themes, try uninstalling the Microsoft Store version and installing Spotify directly from the official website via exe file ([https://www.spotify.com/](https://www.spotify.com/)). 

  Which has generally has better compatibility with Spicetify.

OR: **Try Running the following commands in powershell:**
   ```powershell
   spicetify auto
   spicetify config inject_css 1 replace_colors 1 overwrite_assets 1 inject_theme_js 1
   spicetify apply
   ```
   
Let me know if you continue to have issues after trying these steps!

**Comment by quincynyan** [comment] 2024-06-29 15:21
![image](https://github.com/Astromations/Hazy/assets/65074780/7f6ab1ee-3246-4a20-904c-2ef5e9625f8b)

Comfy seems to be working fine.

**Comment by sanoojes** [comment] 2024-06-29 16:46
ohh i will check on that !

**Comment by Zuntie** [comment] 2024-06-29 19:33
@quincynyan, do you get any errors in your DevTools Console using the Hazy theme?

**Instructions:**

Enabling dev tools:
Run `spicetify enable-devtools` in a terminal or PowerShell.

Opening dev tools in Spotify:
Press `CTRL + SHIFT + I`.

A window should pop up, then click "Console" in the top navigation bar.

**Comment by quincynyan** [comment] 2024-06-30 12:26
Hi, Sorry for the delay. 

Yesterday, I installed Comfy from the marketplace to show it's working, and then today I uninstalled it, then installed Hazy from the marketplace, and it's working again. Before trying Comfy, I've tried uninstalling and reinstalling Hazy multiple times, so I'm sure it isn't an uninstall/reinstall issue fix. Maybe during the installation/uninstallation of Comfy, it fixed something? 

But anyways, yeah Hazy is now working fine, thank you very much! ^w^

**Comment by Zuntie** [comment] 2024-06-30 13:39
> Hi, Sorry for the delay.
> 
> Yesterday, I installed Comfy from the marketplace to show it's working, and then today I uninstalled it, then installed Hazy from the marketplace, and it's working again. Before trying Comfy, I've tried uninstalling and reinstalling Hazy multiple times, so I'm sure it isn't an uninstall/reinstall issue fix. Maybe during the installation/uninstallation of Comfy, it fixed something?
> 
> But anyways, yeah Hazy is now working fine, thank you very much! ^w^

Sounds good! Please go ahead and close this issue :)

**Comment by quincynyan** [comment] 2024-06-30 14:38
Nevermind, issue appeared again.

Devtools without any theme installed:
![image](https://github.com/Astromations/Hazy/assets/65074780/2ff9cfc1-67f8-4e53-b031-c152660f901e)

Devtools with Hazy from marketplace:
![image](https://github.com/Astromations/Hazy/assets/65074780/0d536211-9266-4510-aebb-649d93302e65)

**Comment by Zuntie** [comment] 2024-06-30 15:15
It seems that Hazy isn’t even getting loaded or running. Have you tried the manual installation?

**Closed** 2024-06-30 22:29 UTC
