### ISSUE TITLE
the  left sidebar won't change

### ISSUE THREAD

**Issue by DeathLuck578** [Astromations/Hazy#11] opened 2023-06-25 07:28 UTC
![Screenshot 2023-06-25 142646](https://github.com/Astromations/Hazy/assets/137679577/68fae9da-a411-4428-abf8-e767bffdcb69)

**Comment by Astromations** [comment] 2023-06-25 13:00
Please send me a screenshot of your Spotify and Spicetify versions. They're under this drop down.

![image](https://github.com/Astromations/Hazy/assets/80211195/7b73e6ce-2f4c-4b61-b163-d8749e071572)

**Comment by DeathLuck578** [comment] 2023-06-26 12:06
Spotify for Windows
1.2.13.656.gd13f2059
Spicetify v2.20.2

**Comment by DeathLuck578** [comment] 2023-06-26 12:10
> Please send me a screenshot of your Spotify and Spicetify versions. They're under this drop down.
> 
> ![image](https://user-images.githubusercontent.com/80211195/248557543-7b73e6ce-2f4c-4b61-b163-d8749e071572.png)
Spotify for Windows
1.2.13.656.gd13f2059
Spicetify v2.20.2

**Comment by iamxyntho** [comment] 2023-06-26 17:21
@DeathLuck578 You need to click on "About Spotify" and then click on "Copy Version Info" and then paste it in here.

**Comment by Astromations** [comment] 2023-06-26 17:56
Please update your Spotify. Here is the latest version: 
https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.2.14.1149.ga3ae422d-1027.exe

**Comment by DeathLuck578** [comment] 2023-06-27 16:15
its still wont change 
![Screenshot 2023-06-27 231515](https://github.com/Astromations/Hazy/assets/137679577/4416e295-ae5d-4284-9211-0e2be9d9f3a1)

**Comment by Astromations** [comment] 2023-06-27 22:21
I see you're using SpotX. Spicetify and SpotX are incompatible. That's the cause of the issue. If you're using SpotX for the ad blocker, Spicetify does have that as an extension, but the two clients just won't work together.

**Comment by Astromations** [comment] 2023-06-28 16:40
Closing cause the issue's been diagnosed. Please reopen an issue if your client still isn't working after uninstalling SpotX.

**Closed by Astromations** 2023-06-28 16:40 UTC
